print("Kylie Cezar Relano")
print("Mongpong Santa Cruz, Marinduque")
print("July 20, 2002")
print("BS Information Technology, 1st Year, 2E")
print("Dancing, Playing Mobile Legends, Singing, Video Editing, Photography")